name: ci
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.8
      - uses: actions/checkout@v2
      - run: ls .
      - name: Install setuptools
        run: pip3 install setuptools
      - name: Install co-connect-tools
        run:  pip3 install -e .
      - name: 
        run: |
          etl2cdm  --inputs sample_input_data/patients_sample.csv --structural-mapping sample_input_data/rules1.csv --term-mapping sample_input_data/rules2.csv -v
      - uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: data
          retention-days: 1
