name: ci
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - name: 
        run: |
          pip3 install -r requirements.txt
          python3 etl2cdm.py --inputs sample_input_data/patients_sample.csv --structural-mapping sample_input_data/rules1.csv --term-mapping sample_input_data/rules2.csv -v
      - uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: data
          retention-days: 1
