name: tag-version
on:
  push:
    tags:
    - '*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.8
      - name: check secret
        run: echo {{ secrets.PYPI_KEY }}
